### ISSUE TITLE
Format logs in nested JSON

### ISSUE THREAD

**Issue by thekamaster** [elastic/ecs-logging-java#80] opened 2020-07-06 09:40 UTC
Hi

We are using logstash in our log ingestion pipeline and we found out that logs from this library are not in nested JSON format, which can cause issues in logstash processing, and also correct nested JSON formatting was highly recommanded by our elasticsearch support (as the *beats do).

An example log :
`{"@timestamp":"2020-07-06T09:07:25.481Z", "log.level": "INFO", "message":"Command line argument: -Dcatalina.base=/opt/tomcat", "service.name":"tomcat","event.dataset":"catalina.out","process.thread.name":"main","log.logger":"org.apache.catalina.startup.VersionLoggerListener"}
`

would be :
`{"@timestamp":"2020-07-06T09:07:25.481Z","log":{"level":"INFO","logger":"org.apache.catalina.startup.VersionLoggerListener"},"message":"Command line argument: -Dcatalina.base=/opt/tomcat","service":{"name":"tomcat"},"event":{"dataset":"catalina.out"},"process":{"thread":{"name":"main"}}}`

Can this library output be properly nested ?
Thanks,
Alexandre

**Comment by felixbarny** [comment] 2020-07-06 11:27
Closing as duplicate of https://github.com/elastic/ecs-logging-java/issues/51#issuecomment-621805445.

I feel your pain. Make sure to upvote the referenced Filebeat issue.

**Closed** 2020-07-06 11:38 UTC
